### ISSUE TITLE
easyEXPRESS reference namespace issue.

### ISSUE THREAD

**Issue by TRThurman** [usnistgov/easyexpress-public#15]
**Describe the bug**
The pop-up search for a definition does not respect the interface hierarchy.

**To Reproduce**
1. Go to Derived_shape_element_mim
USE FROM shape_aspect_definition_schema   --  ISO 10303-47
  (apex,
   centre_of_symmetry,
   derived_shape_aspect,
   extension,
   geometric_alignment,
   geometric_intersection,
   parallel_offset,
   perpendicular_to,
   shape_aspect_deriving_relationship,
   tangent);

TYPE dse_shape_model = SELECT BASED_ON shape_model WITH
   (constructive_geometry_representation);
END_TYPE; 

3. Click on 'shape_model'
4. select goto definition
5. results:
SCHEMA Shape_property_assignment_arm;

USE FROM Assembly_structure_arm; -- ISO/TS 10303-1026
USE FROM External_model_arm; -- ISO/TS 10303-1033
USE FROM Geometric_model_relationship_arm; -- ISO/TS 10303-1403
USE FROM Product_view_definition_relationship_arm; -- ISO/TS 10303-1041
USE FROM Property_assignment_arm; -- ISO/TS 10303-1030
...
TYPE **shape_model** = EXTENSIBLE GENERIC_ENTITY SELECT <<<bold indicates highlighted text
  (External_geometric_model,
   Geometric_model);
END_TYPE;

**Expected behavior**

SCHEMA Shape_property_assignment_mim;<<<mim, not arm

(*REFERENCE FROM*) USE FROM Assembly_structure_mim; -- ISO/TS 10303-1026
(*REFERENCE FROM*) USE FROM External_model_mim; -- ISO/TS 10303-1033
USE FROM Geometric_model_relationship_mim; -- ISO/TS 10303-1403
USE FROM Property_assignment_mim; -- ISO/TS 10303-1030
USE FROM Product_view_definition_relationship_mim; -- ISO/TS 10303-1041
...
TYPE **shape_model** = EXTENSIBLE GENERIC_ENTITY SELECT <<<bold indicates highlighted text
  (External_geometric_model,
   Geometric_model);
END_TYPE;
**For STEP developers**
start in Derived_shape_element_mim

**Comment by krimas** [comment]
@TRThurman , the "go to definition" takes you where the type is initially defined, not interfaced.
There is no `shape_model ` type definition in `Shape_property_assignment_mim`;
There might be a scoping issue though. We will investigate.

**Comment by TRThurman** [comment]
Sorry for confusion. Here is corrected data set.

**Describe the bug**
The pop-up search for a definition does not respect the interface hierarchy.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to Derived_shape_element_mim
USE FROM shape_aspect_definition_schema   --  ISO 10303-47
  (apex,
   centre_of_symmetry,
   derived_shape_aspect,
   extension,
   geometric_alignment,
   geometric_intersection,
   parallel_offset,
   perpendicular_to,
   shape_aspect_deriving_relationship,
   tangent);

TYPE dse_shape_model = SELECT BASED_ON shape_model WITH
   (constructive_geometry_representation);
END_TYPE; 

3. Click on 'shape_model'
4. select goto definition
5. results:
SCHEMA Shape_property_assignment_arm;

USE FROM Assembly_structure_arm; -- ISO/TS 10303-1026
USE FROM External_model_arm; -- ISO/TS 10303-1033
USE FROM Geometric_model_relationship_arm; -- ISO/TS 10303-1403
USE FROM Product_view_definition_relationship_arm; -- ISO/TS 10303-1041
USE FROM Property_assignment_arm; -- ISO/TS 10303-1030
...
TYPE **shape_model** = EXTENSIBLE GENERIC_ENTITY SELECT <<<bold indicates highlighted text
  (External_geometric_model,
   Geometric_model);
END_TYPE;

**Expected behavior**

SCHEMA shape_tolerance_schema '{iso standard 10303 part(47) version(7) object(1) shape_tolerance_schema(3)}';

TYPE shape_model = EXTENSIBLE GENERIC_ENTITY SELECT
   (shape_representation);
END_TYPE;

**For STEP developers**
start in Derived_shape_element_mim

**Comment by krimas** [comment]
@TRThurman You're correct, there is a problem in the scope resolution. I started working on it this afternoon and will provide a status update next week.

**Comment by krimas** [comment]
@TRThurman The new updated scope resolution in 0.3.3 should address that issue and others of the same type.

**Comment by TRThurman** [comment]
Sylvere, looks good!
